// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcpnxukjtgdnpbvczhff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjcG54dWtqdGdkbnBidmN6aGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjI4OTQsImV4cCI6MjA2MzgzODg5NH0.DOOqK8A4LB_GeN_l55EzjpbLyT3MmYNBIDLceWK6ch4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);